# Generated by Django 3.1 on 2022-02-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallary', 'verbose_name_plural': 'product gallary'},
        ),
    ]
